---

- block:
    - name: testing | Ensure inspec is present
      win_chocolatey:
        name: inspec
        state: present

    - name: testing | run windows-baseline
      win_command: "c:\\opscode\\inspec\\bin\\inspec.bat exec https://github.com/juju4/windows-baseline >{{ harden_win_log_dir }}\\inspec.log"
      ignore_errors: true

  when: harden_win_testing_inspec

# https://blog.malwarebytes.com/security-world/technology/2017/11/when-you-shouldnt-trust-a-trusted-root-certificate/
# FIXME! FATAL ERROR DURING FILE TRANSFER: ...
#- name: Export trusted root certificates
#  shell: Get-ChildItem -Path cert:\currentuser\AuthRoot -Recurse | select Thumbprint, FriendlyName, Subject | ConvertTo-Html | Set-Content c:\users\public\desktop\certificates.html

- include_tasks: testing-applocker.yml
  when: harden_win_testing_applocker

- include_tasks: testing-uac.yml
  when: harden_win_testing_uac

- include_tasks: testing-opf.yml
  when: harden_win_testing_opf

- include_tasks: testing-privesc.yml
  when: harden_win_testing_privesc

- include_tasks: testing-msoffice.yml
  when: harden_win_testing_msoffice

- include_tasks: testing-speculative.yml
  when: harden_win_testing_speculative

- include_tasks: testing-intelme.yml
  when: harden_win_testing_intelme

- include_tasks: testing-iad.yml
  when: harden_win_testing_iad

- include_tasks: testing-detections.yml
  when: harden_win_testing_detections

# keep last. if defender catches it, may need to restart to complete cleaning/have ansible working again
- include_tasks: testing-mimikatz.yml
  when: harden_win_testing_mimikatz
