---
# https://findingbad.blogspot.ca/2018/01/what-are-your-tools-detecting.html
# https://www.redcanary.com/blog/atomic-red-team-tests-catching-dragon-tail/
# https://github.com/redcanaryco/atomic-red-team
# https://raw.githubusercontent.com/redcanaryco/atomic-red-team/master/ARTifacts/Chain_Reactions/chain_reaction_DragonsTail.bat
# https://github.com/NextronSystems/APTSimulator/
# https://github.com/NextronSystems/APTSimulator/releases/download/v0.4.1/APTSimulator_pw_apt.zip

- name: 7-zip installation
  win_chocolatey:
    name: 7zip
    state: present
    upgrade: no

- name: Testing Detections | Download NextronSystems APTSimulator
  get_url:
    url: https://github.com/NextronSystems/APTSimulator/releases/download/v0.4.1/APTSimulator_pw_apt.zip
    dest: "{{ harden_win_temp_dir }}/APTSimulator_pw_apt.zip"

- name: Testing Detections | Unarchive NextronSystems APTSimulator
  win_shell: 7zip e -y -tzip -papt APTSimulator_pw_apt.zip
  args:
    chdir: "{{ harden_win_temp_dir }}"

- name: Testing Detections | Execute NextronSystems APTSimulator
  win_shell: APTSimulator.bat
  args:
    chdir: "{{ harden_win_temp_dir }}/APTSimulator"

- name: Testing Detections | Download Redcanary Atomic-red-team
  git:
    repo: https://github.com/redcanaryco/atomic-red-team.git
    dest: "{{ harden_win_temp_dir }}/atomic-red-team"

- name: Testing Detections | Executing Redcanary Atomic-red-team chain_reaction_DragonsTail.bat
  win_shell: chain_reaction_DragonsTail.bat
  args:
    chdir: "{{ harden_win_temp_dir }}/atomic-red-team/ARTifacts/Chain_Reactions"
