---

- block:
    - name: testing | Ensure inspec is present
      win_chocolatey:
        name: inspec
        state: present

    - name: Restrict permissions for inspec directories
      win_acl:
        path: "{{ item.p }}"
        user: "{{ item.u }}"
        rights: "{{ item.r }}"
        type: "{{ item.t }}"
        state: "{{ item.s }}"
        inherit: "{{ item.i }}"
        propagation: "{{ item.p }}"
      with_items:
        - { p: "c:\\opscode", u: 'BUILTIN\Users', r: 'write,append', t: allow, s: absent, i: 'ContainerInherit, ObjectInherit', p: 'InheritOnly' }

    - name: testing | run windows-baseline
      win_command: "c:\\opscode\\inspec\\bin\\inspec.bat exec https://github.com/juju4/windows-baseline >{{ harden_win_log_dir }}\\inspec.log"
      ignore_errors: true

    - name: testing | inspec results
      win_shell: "Get-Content -Path \"{{ harden_win_log_dir }}\\inspec.log\""
      changed_when: false
      ignore_errors: true

  when: harden_win_testing_inspec

# https://blog.malwarebytes.com/security-world/technology/2017/11/when-you-shouldnt-trust-a-trusted-root-certificate/
# FIXME! FATAL ERROR DURING FILE TRANSFER: ...
#- name: Export trusted root certificates
#  shell: Get-ChildItem -Path cert:\currentuser\AuthRoot -Recurse | select Thumbprint, FriendlyName, Subject | ConvertTo-Html | Set-Content c:\users\public\desktop\certificates.html

- set_fact:
    ansible_become_password: "_Password_CI_CD_to_be_revoked1_"

## FIXME! failing on second pass, https://groups.google.com/forum/#!topic/ansible-project/_ydkYXZibrM
- name: Ensure user _test is present
  win_user:
    name: _test
    password: "{{ ansible_become_password }}"
    state: present
    groups:
      - Users

- include: testing-uac.yml
  when: harden_win_testing_uac

- include: testing-opf.yml
  when: harden_win_testing_opf

- include: testing-speculative.yml
  when: harden_win_testing_speculative

- include: testing-intelme.yml
  when: harden_win_testing_intelme

- include: testing-iad.yml
  when: harden_win_testing_iad

# keep last. if defender catches it, may need to restart to complete cleaning/have ansible working again
- include: testing-mimikatz.yml
  when: harden_win_testing_mimikatz

- name: Remove user _test
  win_user:
    name: _test
    state: absent
