---

# https://github.com/iadgov/Secure-Host-Baseline
- name: IAD | retrieve Secure-Host-Baseline
  win_command: "git.exe clone https://github.com/iadgov/Secure-Host-Baseline.git \"{{ harden_win_temp_dir }}\\Secure-Host-Baseline\""
#  git:
#    repo: https://github.com/iadgov/Secure-Host-Baseline.git
#    dest: "{{ harden_win_temp_dir }}/Secure-Host-Baseline"
#       version: HEAD
#  become: yes
#  become_user: _test
# OR download
#  win_url:
#    src: https://github.com/iadgov/Secure-Host-Baseline/archive/master.zip
#    dest: "{{ harden_win_temp_dir }}/Secure-Host-Baseline-master.zip"

#- name: Unsure file is unblocked
#  win_shell: "Unblock-File -Path '.\Secure-Host-Baseline-master.zip'"
#  args:
#    chdir: "{{ harden_win_temp_dir }}"

#- name: Unarchive file
#  win_unzip:
#    src: "{{ harden_win_temp_dir }}/Secure-Host-Baseline-master.zip"
#    dest: "{{ harden_win_temp_dir }}/Secure-Host-Baseline"

- name: IAD | Apply policies
  win_shell: "{{ item }}"
  with_items:
    - Import-Module -Name .\\Secure-Host-Baseline\\Scripts\\GroupPolicy.psm1
    - "Invoke-ApplySecureHostBaseline -Path \"{{ harden_win_temp_dir }}\\Secure-Host-Baseline\" -PolicyNames AppLocker,Chrome,Windows -PolicyMode Audit"
  args:
    chdir: "{{ harden_win_temp_dir }}"
  when: harden_win_testing_iad_apply

- name: IAD | Audit policies
  win_shell: "{{ item }}"
  with_items:
    - Import-Module -Name .\\Compliance.psm1
#    - Test-Compliance -Path '..\\..\\Adobe Reader\\Compliance\\AdobeReaderDC.audit'
    - Test-Compliance -Path '..\\..\\Chrome\\Compliance\\GoogleChrome.audit'
#    - Test-Compliance -Path '..\\..\\EMET\\Compliance\\EMET_5.5.audit'
    - Test-Compliance -Path '..\\..\\Internet Explorer\\Compliance\\InternetExplorer11.audit'
    - Test-Compliance -Path '..\\..\\Windows\\Compliance\\Windows10.audit'
  args:
    chdir: "{{ harden_win_temp_dir }}\\Secure-Host-Baseline\\Compliance\\Scripts"
  register: iadresults
- debug: var=iadresults

