---
## https://blogs.windows.com/msedgedev/2015/08/26/how-microsoft-edge-and-internet-explorer-11-on-windows-10-work-better-together-in-the-enterprise/#s4vAKTKvz328jwjY.97 Enterprise Mode Site List
## http://www.morgantechspace.com/2013/11/Enable-File-System-Auditing-in-Windows.html
## https://4sysops.com/archives/deny-and-allow-workstation-logons-with-group-policy/
## https://www.reddit.com/r/sysadmin/comments/1yzjul/restricting_interactive_logon_but_allow_runas/
## http://www.authlite.com/kb/allow-runas-but-block-interactive-logon/
## * Remove Debug Privileges
## https://technet.microsoft.com/en-us/library/dn221969(v=ws.11).aspx
## https://blogs.msdn.microsoft.com/oldnewthing/20080314-00/?p=23113/
## https://www.sans.org/reading-room/whitepapers/testing/passthehash-attacks-tools-and-mitigation-33283
## https://iase.disa.mil/stigs/gpo/Pages/index.aspx

- name: copy gpo template to target computer
  win_template:
    src: "{{ harden_win_gpo_inf }}"
    dest: "{{ harden_win_temp_dir }}\\{{ harden_win_gpo_inf | regex_replace('.j2$', '') }}"

## Windows Server 2003, Windows Server 2003 R2, Windows Server 2003 with SP1, Windows Server 2003 with SP2
## https://technet.microsoft.com/en-ca/library/cc776625%28v=ws.10%29.aspx
- block:
    - name: load gpo configuration locally - secedit
      win_command: "secedit /configure /cfg {{ harden_win_temp_dir }}\\{{ harden_win_gpo_inf | regex_replace('.j2$', '') }} /db {{ harden_win_gpo_db }} /log {{ harden_win_gpo_log }} /verbose"
      args:
        creates: "{{ harden_win_gpo_log }}"
      ignore_errors: true
## require Windows Script Host
#  raw: "msiexec /qb /i c:\Program Files (x86)\Microsoft Security Compliance Manager\LGPO\LocalGPO.msi"
#  raw: "csript c:\Program Files (x86)\LocalGPO\LocalGPO.wsf"

    - name: Check secedit log file
      win_shell: "Get-Content -Path {{ harden_win_gpo_log }}"
      changed_when: false
      ignore_errors: true
  when: harden_win_gpo_local_action == 'secedit'

- block:
# https://blogs.msdn.microsoft.com/powershell/2016/05/20/new-group-policy-cmdlets-for-nano-server/
    - name: load gpo configuration locally - Restore-SecurityPolicy
      win_shell: "Restore-SecurityPolicy -Path \"{{ harden_win_temp_dir }}\\{{ harden_win_gpo_inf | regex_replace('.j2$', '') }}\""
  when: harden_win_gpo_local_action == 'ps'

## Microsoft Security Compliance Manager, https://technet.microsoft.com/library/cc677002.aspx
## https://technet.microsoft.com/en-us/library/jj966254%28v=ws.11%29.aspx

## Administrative Templates for Windows PowerShell (msi)
## https://www.microsoft.com/en-us/download/details.aspx?id=25119

## Configure Network Level Authentication for Remote Desktop Services Connections, win2008r2+
## https://technet.microsoft.com/en-us/library/cc732713%28v=ws.11%29.aspx

## (LLMNR) Computer Configuration->Administrative Templates->Network->DNS client: Turn off multicast name resolution

