---

# https://www.stigviewer.com/stig/windows_10/2016-11-03/finding/V-63373
- name: Permissions for system files and directories must conform to minimum requirements. - C:
  win_acl:
    path: C:\
    user: "{{ item.u }}"
    rights: "{{ item.r }}"
    type: "{{ item.t }}"
    state: present
    inherit: "{{ item.i }}"
    propagation: "{{ item.p }}"
  with_items:
    - { u: 'Administrators', r: 'FullControl', t: 'allow', i: 'ContainerInherit, ObjectInherit', p: 'InheritOnly' }
    - { u: 'SYSTEM', r: 'FullControl', t: 'allow', i: 'ContainerInherit, ObjectInherit', p: 'InheritOnly' }
    - { u: 'Users', r: 'ReadAndExecute', t: 'allow', i: 'ContainerInherit, ObjectInherit', p: 'InheritOnly' }
    - { u: 'Authenticated Users', r: 'Modify', t: 'allow', i: 'ContainerInherit, ObjectInherit', p: 'InheritOnly' }
#    - { u: 'Authenticated Users', r: 'CreateDirectories, AppendData', t: 'allow', i: 'None', p: 'NoPropagateInherit' }

# https://www.stigviewer.com/stig/windows_10/2015-11-30/finding/V-63593
- name: Permissions for registry hive must conform to minimum requirements. - HKLM\Security
  win_acl:
    path: HKLM:\SECURITY
    user: "{{ item.u }}"
    rights: "{{ item.r }}"
    type: "{{ item.t }}"
    state: present
    inherit: "{{ item.i }}"
    propagation: "{{ item.p }}"
  with_items:
    - { u: 'Administrators', r: 'FullControl', t: 'allow', i: 'ContainerInherit, ObjectInherit', p: 'InheritOnly' } # Special?
    - { u: 'SYSTEM', r: 'FullControl', t: 'allow', i: 'ContainerInherit, ObjectInherit', p: 'InheritOnly' }

- name: Permissions for registry hive must conform to minimum requirements. - HKLM\Software
  win_acl:
    path: HKLM:\SOFTWARE
    user: "{{ item.u }}"
    rights: "{{ item.r }}"
    type: "{{ item.t }}"
    state: present
    inherit: "{{ item.i }}"
    propagation: "{{ item.p }}"
  with_items:
    - { u: 'Administrators', r: 'FullControl', t: 'allow', i: 'ContainerInherit, ObjectInherit', p: 'InheritOnly' } # Special?
    - { u: 'SYSTEM', r: 'FullControl', t: 'allow', i: 'ContainerInherit, ObjectInherit', p: 'InheritOnly' }
    - { u: 'CREATOR OWNER', r: 'FullControl', t: 'allow', i: 'ContainerInherit, ObjectInherit', p: 'InheritOnly' }
    - { u: 'ALL APPLICATION PACKAGES', r: 'Read', t: 'allow', i: 'ContainerInherit, ObjectInherit', p: 'InheritOnly' }
    - { u: 'Users', r: 'Read', t: 'allow', i: 'ContainerInherit, ObjectInherit', p: 'InheritOnly' }

- name: Permissions for registry hive must conform to minimum requirements. - HKLM\System
  win_acl:
    path: HKLM:\SYSTEM
    user: "{{ item.u }}"
    rights: "{{ item.r }}"
    type: "{{ item.t }}"
    state: present
    inherit: "{{ item.i }}"
    propagation: "{{ item.p }}"
  with_items:
    - { u: 'Administrators', r: 'FullControl', t: 'allow', i: 'ContainerInherit, ObjectInherit', p: 'InheritOnly' } # Special?
    - { u: 'SYSTEM', r: 'FullControl', t: 'allow', i: 'ContainerInherit, ObjectInherit', p: 'InheritOnly' }
    - { u: 'CREATOR OWNER', r: 'FullControl', t: 'allow', i: 'ContainerInherit, ObjectInherit', p: 'InheritOnly' }
    - { u: 'ALL APPLICATION PACKAGES', r: 'Read', t: 'allow', i: 'ContainerInherit, ObjectInherit', p: 'InheritOnly' }
    - { u: 'Users', r: 'Read', t: 'allow', i: 'ContainerInherit, ObjectInherit', p: 'InheritOnly' }

